### PR TITLE
Product type with axes

### PR DESCRIPTION
**Pull request by msdemlei**
This is a change for more or less internal review; comments have been circulated by mail)

### CODE REVIEW

**Review by pdowler — COMMENTED** [review]
the "backwards compatible" level 2 terms (eg `image`) are missing the skos:broader indication.... is that on purpose?

**Comment by msdemlei** [comment]
On Mon, Jun 26, 2023 at 12:42:36PM -0700, Patrick Dowler wrote:
> the "backwards compatible" level 2 terms (eg `image`) are missing
> the skos:broader iindication.... is that on purpose?

Ah, no, that's not related to backwards compatible.  They are simply
in the "primary tree" that in SKOS CSV works as in our strict tree
vocabularies.  For image:

  spatially-resolved-dataset;1;Spatially Resolved;A
  image;2;Image;An astronomical image, typically wit

Note the 1 and 2: spatially-resolved-dataset is a parent of image,
just as in datalink/core and friends.

It's probably better to look at the rendered thing for review:

http://www.ivoa.net/rdf/product-type/2023-06-26/product-type.html

**Comment by pdowler** [comment]
oh, so in converting the text representation to skos the order matters and a level 2 concept is implicitly a narrower term than the level 1 concept above it?

I saw `;skos:broader(spatially-resolved-dataset) skos:broader(spectrally-resolved-dataset)` in spectral-cube and inferred that this was the way to specify parent(s)... 

So spectral-cube, time-cube, and polarization cube have implicit parent cube because they are 3 and cube is the 2 above them?

Could you qualify image with `;skos:broader(spatially-resolved-dataset)` as well? Would being explicit be better?

**Comment by msdemlei** [comment]
On Tue, Jun 27, 2023 at 04:36:11PM -0700, Patrick Dowler wrote:
> oh, so in converting the text representation to skos the order
> matters and a level 2 concept is implicitly a narrower term than
> the level 1 concept above it?

Yes, just as in our tree-based vocabularies, except in SKOS there can
be multiple wider concepts for a single concept, which is why there
are occasionally these extra skos:broader relations.

> So spectral-cube, time-cube, and polarization cube have implicit
> parent cube because they are 3 and cube is the 2 above them?

Yes.

> Could you qualify image with
> `;skos:broader(spatially-resolved-dataset)` as well? Would being
> explicit be better?

Well... I was hoping being consistent with our other vocabularies and
being concise would win the day.

I'd argue that you'd usually inspect the CSV only in the form of
diffs and would do the sort of global review in some formatted
document, as in our HTML rendering or perhaps using an RDF tool.
Hence, being explicit in the CSV perhaps is not a major design goal.

If, on the other hand, we actually spell out the full hierarchy via
relationships, Norman's CSV doesn't leave a lot of advantages, and
then there's little reason not to use an (admittedly somewhat more
compliated) standard RDF serialisation (as in: Turtle).

**Pull request merged**
